### ISSUE TITLE
react-redux-router necessary?

### ISSUE THREAD

**Issue by nwinch** [Prismatik/react-redux-starter#1]
@Nicktho Should we add this?  Could it be too opinionated for boilerplate?

**Comment by Nicktho** [comment]
The reasoning behind react-redux-router is to pull history state into the state tree. I personally find it jarring to deal with every other bit of application state in redux, then having to pass down routeParams as props from `react-router`, as well as managing navigation through the history library (`history.push()`), rather than dispatching an action to trigger navigation (`dispatch(push())`) and pulling the location off the state tree with my other data.

I'd vote if we're keeping `react-router`, to keep `react-redux-router`.

**Comment by nwinch** [comment]
Oh yeah, I get why we'd use it, but have we used `react-redux-router` on many projects?

Let's add commonly vetted plugins/libs to the boilerplate that we have used/will continue to use.  Adding ones we think are good ideas I want to at least ask the question before we add willy nilly.  Router state in state tree makes sense to me, but does it for everyone else?

**Comment by Nicktho** [comment]
Sure, that makes sense, let's leave it out until we use it on a project first.
